# Generated by Django 5.2.7 on 2025-10-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, upload_to='phontos/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
