# Generated by Django 5.2.7 on 2025-10-20 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('age', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)], verbose_name='Возраст')),
                ('sex', models.CharField(choices=[('m', 'мужчина'), ('f', 'женщина'), ('d', 'Программист')], max_length=20, verbose_name='Пол')),
                ('active', models.BooleanField(verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['surname'],
                'indexes': [models.Index(fields=['surname'], name='main_studen_surname_307540_idx')],
                'unique_together': {('name', 'surname')},
            },
        ),
    ]
