# Generated by Django 5.2.7 on 2025-10-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_course_student_course_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('m', 'мужчина'), ('f', 'женщина'), ('d', 'программист')], max_length=20, verbose_name='Пол'),
        ),
    ]
